ALTER TABLE `notes` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `users` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `projects` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `product` CONVERT TO CHARACTER SET utf8;
